import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header/header";

const openSans = Open_Sans({
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "My Profile",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
 return (
   <html lang="en">
     <body className={openSans.className}>

       <Header />
       <div className="bg-home bg-no-repeat bg-cover">
         <div className="bg-brown w-screen">
           {children}
         </div>
       </div>
      
     </body>
   </html>
 );
}
